### ISSUE TITLE
Add "secret/data" to my "objectPath" HashiCorp Vault

### ISSUE THREAD

**Issue by carnei-ro** [deislabs/secrets-store-csi-driver#91]
Just tried to run the example with CS In Line Volume, but my secret path in HashiCorp Vault is "sandbox/k8s_infra/marketplace/account/my-new-app/db"
I spected that driver requests the path "/sandbox/data/k8s_infra/marketplace/account/my-new-app/db" instead its try to request "secret/data/sandbox/k8s_infra/marketplace/account/my-new-app/db".

Here my pod spec:
```
kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
  namespace: my-new-app
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.com
        readOnly: true
        volumeAttributes:
          providerName: "vault" # Vault ou azure
          roleName: "k8s_sre_infra_sandbox_own_namespace_role"
          vaultAddress: "https://vault.dc.infra.ifood-sandbox.com.br"
          objects:  |
            array:
              - |
                objectPath: "sandbox/k8s_infra/marketplace/account/my-new-app/db"
                objectName: "db_password"
              - |
                objectPath: "sandbox/k8s_infra/marketplace/account/my-new-app/app"
                objectName: "bla"
```
